version: '3.3'

services:
  llmbot:
    image: sudoskys/llmbot:latest
    restart: on-failure
    depends_on:
      - redis
      - rabbitmq
    environment:
      AMQP_DSN: amqp://admin:admin@rabbitmq:5672
      REDIS_DSN: redis://redis:6379/0
    env_file:
      - .env
    networks:
      - app-tier
    command: [ "./wait-for-mysql.sh", "rabbitmq:5672", "--", "sh", "./start.sh" ]

  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./data:/var/lib/rabbitmq
    networks:
      - app-tier
  redis:
    restart: on-failure
    container_name: redis-server
    image: redis:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
