version: '3.9'

services:
  openaibot:
    image: sudoskys/llmbot:main
    command: python3 start_sender.py&python3 start_receiver.py
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-tier
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-tier
  redis:
    image: redis:latest
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
