version: '3.9'

services:
  llmbot:
    image: sudoskys/llmbot:latest
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env
    networks:
      - app-tier
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./data:/var/lib/rabbitmq
    networks:
      - app-tier
  redis:
    restart: on-failure
    container_name: redis-server
    image: redis:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
